package tools

type mockDB struct{}

var mockClubs = []Club{
	{
    Id: "1",
    Name: "Mid-Missouri Radio Control Association",
    BriefDescription: "An AMA-chartered club in Columbia, MO, offering a paved runway and various RC flying events.",
    WebsiteUrl: "https://www.mmrca.org/",
    Location: "Columbia, MO",
    KeyFeatures: "Paved runway, community events, training programs",
    Address: Address{
      Street: "2810 S. Coats Lane",
      City: "Columbia",
      State: "MO",
      Zip: "65203",
    },
    Latitude: 38.9517,
    Longitude: -92.3341,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "2",
    Name: "Saint Louis Radio Control Flying Association",
    BriefDescription: "An AMA-chartered club located in Eureka, MO, featuring a 42′ by 600′ paved runway and various RC flying events.",
    WebsiteUrl: "https://www.slrcfa.com/",
    Location: "Eureka, MO",
    KeyFeatures: "Paved runway, community events, training programs",
    Address: Address{
      Street: "Off the Chapman Road",
      City: "Eureka",
      State: "MO",
      Zip: "63025",
    },
    Latitude: 38.4875,
    Longitude: -90.5391,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "3",
    Name: "Kansas City Radio Control",
    BriefDescription: "An AMA-chartered club in Kansas City, MO, offering a flying field and various RC flying events.",
    WebsiteUrl: "https://www.kcradiocontrol.com/",
    Location: "Kansas City, MO",
    KeyFeatures: "Flying field, community events, training programs",
    Address: Address{
      Street: "Off the Chapman Road",
      City: "Kansas City",
      State: "MO",
      Zip: "64153",
    },
    Latitude: 39.2975,
    Longitude: -94.6811,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "4",
    Name: "Springfield RC Club",
    BriefDescription: "An AMA Gold Leader Club located in Fair Grove, MO, offering a flying field and various RC flying events.",
    WebsiteUrl: "https://www.springfieldrcclub.org/",
    Location: "Fair Grove, MO",
    KeyFeatures: "Flying field, community events, training programs",
    Address: Address{
      Street: "2320 E State Hwy KK",
      City: "Fair Grove",
      State: "MO",
      Zip: "65648",
    },
    Latitude: 37.331,
    Longitude: -93.2462,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "5",
    Name: "Mineral Area Modeling Association",
    BriefDescription: "An AMA-chartered club in Park Hills, MO, offering a flying field and various RC flying events.",
    WebsiteUrl: "https://www.facebook.com/groups/rcmama/",
    Location: "Park Hills, MO",
    KeyFeatures: "Flying field, community events, training programs",
    Address: Address{
      Street: "St. Joe Park",
      City: "Park Hills",
      State: "MO",
      Zip: "63601",
    },
    Latitude: 37.8161,
    Longitude: -90.5311,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "6",
    Name: "Jefferson City Radio Control Club",
    BriefDescription: "An AMA-chartered club in Jefferson City, MO, offering a flying field and various RC flying events.",
    WebsiteUrl: "https://www.jcparks.com/jc-radio-control-club/",
    Location: "Jefferson City, MO",
    KeyFeatures: "Flying field, community events, training programs",
    Address: Address{
      Street: "5601 Rainbow Dr",
      City: "Jefferson City",
      State: "MO",
      Zip: "65109",
    },
    Latitude: 38.5721,
    Longitude: -92.1781,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "7",
    Name: "Signal Chasers R/C Flying Club",
    BriefDescription: "An AMA-chartered club near Pacific, MO, offering a flying field and various RC flying events.",
    WebsiteUrl: "https://signalchaserscom.wordpress.com/",
    Location: "Pacific, MO",
    KeyFeatures: "Flying field, community events, training programs",
    Address: Address{
      Street: "Bend Road (Hiway N)",
      City: "Pacific",
      State: "MO",
      Zip: "63069",
    },
    Latitude: 38.4325,
    Longitude: -90.7731,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "8",
    Name: "Lafayette Esquadrille Control Line Club",
    BriefDescription: "An AMA-chartered club in St. Louis, MO, specializing in control line model airplanes.",
    WebsiteUrl: "https://lafayetteesquadrillecl.wordpress.com/",
    Location: "St. Louis, MO",
    KeyFeatures: "Control line flying, community events, training programs",
    Address: Address{
      Street: "Buder Park",
      City: "St. Louis",
      State: "MO",
      Zip: "63129",
    },
    Latitude: 38.515,
    Longitude: -90.2925,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "9",
    Name: "Phantom Flyers RC Club",
    BriefDescription: "One of the oldest AMA-chartered RC clubs in the U.S., located in St. Louis, MO.",
    WebsiteUrl: "https://www.phantomflyersrc.com/",
    Location: "St. Louis, MO",
    KeyFeatures: "Long history, community events, training programs",
    Address: Address{
      Street: "Off the Chapman Road",
      City: "St. Louis",
      State: "MO",
      Zip: "63123",
    },
    Latitude: 38.54,
    Longitude: -90.3145,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "10",
    Name: "St. Charles County Radio Control Club",
    BriefDescription: "An AMA-chartered club in St. Charles, MO, offering a flying field and various RC flying events.",
    WebsiteUrl: "https://www.stcharlesrcclub.com/",
    Location: "St. Charles, MO",
    KeyFeatures: "Flying field, community events, training programs",
    Address: Address{
      Street: "Off the Chapman Road",
      City: "St. Charles",
      State: "MO",
      Zip: "63301",
    },
    Latitude: 38.7885,
    Longitude: -90.4975,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "11",
    Name: "Cape Girardeau RC Club",
    BriefDescription: "An AMA-chartered club in Cape Girardeau, MO, offering a flying field and various RC flying events.",
    WebsiteUrl: "https://www.capeairrc.com/",
    Location: "Cape Girardeau, MO",
    KeyFeatures: "Flying field, community events, training programs",
    Address: Address{
      Street: "Off the Chapman Road",
      City: "Cape Girardeau",
      State: "MO",
      Zip: "63701",
    },
    Latitude: 37.305,
    Longitude: -89.518,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "12",
    Name: "Jefferson County Radio Control Club",
    BriefDescription: "An AMA-chartered club in Hillsboro, MO, offering a flying field and various RC flying events.",
    WebsiteUrl: "https://www.jcrcclub.com/",
    Location: "Hillsboro, MO",
    KeyFeatures: "Flying field, community events, training programs",
    Address: Address{
      Street: "Off the Chapman Road",
      City: "Hillsboro",
      State: "MO",
      Zip: "63050",
    },
    Latitude: 38.2095,
    Longitude: -90.5725,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "13",
    Name: "Ozark Mountain RC Club",
    BriefDescription: "An AMA-chartered club in Branson, MO, offering a flying field and various RC flying events.",
    WebsiteUrl: "https://www.ozarkmountainrc.com/",
    Location: "Branson, MO",
    KeyFeatures: "Flying field, community events, training programs",
    Address: Address{
      Street: "Off the Chapman Road",
      City: "Branson",
      State: "MO",
      Zip: "65616",
    },
    Latitude: 36.643,
    Longitude: -93.2175,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "14",
    Name: "Northwest Missouri RC Club",
    BriefDescription: "An AMA-chartered club in St. Joseph, MO, offering a flying field and various RC flying events.",
    WebsiteUrl: "https://www.nwmorcc.com/",
    Location: "St. Joseph, MO",
    KeyFeatures: "Flying field, community events, training programs",
    Address: Address{
      Street: "Off the Chapman Road",
      City: "St. Joseph",
      State: "MO",
      Zip: "64507",
    },
    Latitude: 39.7675,
    Longitude: -94.8105,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "15",
    Name: "Kansas City Radio Control Association",
    BriefDescription: "Large, long-running AMA Gold Leader club serving the Kansas City / Lee's Summit area with multiple runways and public events.",
    WebsiteUrl: "https://www.kcradiocontrol.com/",
    Location: "Lee's Summit, MO",
    KeyFeatures: "Owned field (Charles Reed Memorial Flying Field), training, warbird/classics fly-ins, public events",
    Address: Address{
      Street: "3899 Rennau Dr (Fleming Park/Charles Reed Memorial Flying Field)",
      City: "Lee's Summit",
      State: "MO",
      Zip: "64064",
    },
    Latitude: 38.977202,
    Longitude: -94.342007,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "16",
    Name: "Phantom Flyers R/C Club",
    BriefDescription: "Historic, AMA-chartered St. Charles club with a large field and a long event calendar (pattern, fun-fly, swap meets).",
    WebsiteUrl: "https://www.phantomflyersrc.com/",
    Location: "Saint Charles, MO",
    KeyFeatures: "Large grass field, pattern contests, swap meets, member training",
    Address: Address{
      Street: "4299 Wiedey Rd",
      City: "Saint Charles",
      State: "MO",
      Zip: "63301",
    },
    Latitude: 38.840951,
    Longitude: -90.419502,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "17",
    Name: "Saint Louis Radio Control Flying Association (SLRCFA)",
    BriefDescription: "Major St. Louis area AMA-chartered club with a large field, jets, big-bird events, and open houses.",
    WebsiteUrl: "https://slrcfa.com/",
    Location: "Eureka, MO",
    KeyFeatures: "Asphalt & grass runways, jet events, camps & flys, public open houses",
    Address: Address{
      Street: "788 Augustine Rd",
      City: "Eureka",
      State: "MO",
      Zip: "63025",
    },
    Latitude: 38.4823098,
    Longitude: -90.60782,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "18",
    Name: "Springfield RC Club (BlackSheep Squadron)",
    BriefDescription: "Active southwest-Missouri club running community events, contests and pilot training north of Springfield.",
    WebsiteUrl: "https://www.springfieldrcclub.org/",
    Location: "Springfield, MO",
    KeyFeatures: "Field flying, public demos, contests, youth outreach",
    Address: Address{
      Street: "2260 E State Hwy KK (field area)",
      City: "Springfield",
      State: "MO",
      Zip: "",
    },
    Latitude: 0,
    Longitude: 0,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "19",
    Name: "Mid-Missouri Radio Control Association (MMRCA)",
    BriefDescription: "Columbia area AMA club with an established flying site and active calendar (instruction & events).",
    WebsiteUrl: "https://www.mmrca.org/",
    Location: "Columbia, MO",
    KeyFeatures: "Owned field, pilot instruction, community events",
    Address: Address{
      Street: "2810 S Coats Ln",
      City: "Columbia",
      State: "MO",
      Zip: "65203",
    },
    Latitude: 38.926388,
    Longitude: -92.422222,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "20",
    Name: "Jefferson City Radio Control Club",
    BriefDescription: "Capital-area club flying at Joseph C. Miller Flying Field, offering instruction, public demos and community events.",
    WebsiteUrl: "https://www.modelaircraft.org/club/jefferson-city-rc-club",
    Location: "Jefferson City, MO",
    KeyFeatures: "Asphalt runway, covered shelter, pilot instruction, youth outreach",
    Address: Address{
      Street: "5601 Rainbow Dr (Joseph C. Miller Flying Field)",
      City: "Jefferson City",
      State: "MO",
      Zip: "65109",
    },
    Latitude: 38.589288,
    Longitude: -92.299912,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "21",
    Name: "Sedalia R/C Flyers",
    BriefDescription: "Central Missouri club that flies at the State Fairgrounds with public flying and club events.",
    WebsiteUrl: "https://sedaliarcflyers.com/wordpress/",
    Location: "Sedalia, MO",
    KeyFeatures: "State Fairgrounds field, seasonal events, swap meets",
    Address: Address{
      Street: "Missouri State Fairgrounds Gate 9 (off Clarendon Rd)",
      City: "Sedalia",
      State: "MO",
      Zip: "65301",
    },
    Latitude: 38.690075,
    Longitude: -93.266894,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "22",
    Name: "Mineral Area Modeling Association (MAMA)",
    BriefDescription: "Southeast-Missouri AMA-chartered club flying at St. Joe State Park / Pimville Rd field.",
    WebsiteUrl: "https://www.modelaircraft.org/club/mineral-area-modeling-association",
    Location: "Park Hills, MO",
    KeyFeatures: "Park field, public demos, community outreach",
    Address: Address{
      Street: "3380 Pimville Rd",
      City: "Park Hills",
      State: "MO",
      Zip: "63601",
    },
    Latitude: 37.819779,
    Longitude: -90.531898,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "23",
    Name: "St. Joe Barnstormers",
    BriefDescription: "Northwest Missouri club (St. Joseph area) — hosts fun-flies and public events at a dedicated Field of Dreams site.",
    WebsiteUrl: "https://www.modelaircraft.org/club/st-joe-barnstormers",
    Location: "Saint Joseph, MO",
    KeyFeatures: "Field of Dreams flying field, fun-flys, community events",
    Address: Address{
      Street: "7274 Missouri Hwy 6",
      City: "Saint Joseph",
      State: "MO",
      Zip: "64507",
    },
    Latitude: 39.779611,
    Longitude: -94.733538,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "24",
    Name: "Southeast Missouri Modelers Association (SEMMA)",
    BriefDescription: "Cape Girardeau area AMA-chartered modelers association — active public demonstrations and community events.",
    WebsiteUrl: "https://semmarc.net/",
    Location: "Cape Girardeau, MO",
    KeyFeatures: "Public demos, community outreach, airport and park events",
    Address: Address{
      Street: "441 Gizmo Ln (Galaxy Park / flying site)",
      City: "Cape Girardeau",
      State: "MO",
      Zip: "63701",
    },
    Latitude: 37.35301,
    Longitude: -89.48831,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "25",
    Name: "Ozark Mountain Barnstormers",
    BriefDescription: "Springfield-area club (Ozarks) — group for general RC flying and local contests.",
    WebsiteUrl: "https://www.rcgroups.com/forums/showthread.php?1565415-Ozark-Mountain-Barnstormers",
    Location: "Springfield / Ozark area, MO",
    KeyFeatures: "Local contests, club fly-ins, community events",
    Address: Address{
      Street: "",
      City: "Springfield",
      State: "MO",
      Zip: "",
    },
    Latitude: 0,
    Longitude: 0,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "26",
    Name: "Lake Ozark Radio Control Society",
    BriefDescription: "Central-Missouri float/field club that runs regular events and fly-ins near the Lake of the Ozarks.",
    WebsiteUrl: "https://www.facebook.com/groups/485692538658261",
    Location: "Eldon / Lake Ozark area, MO",
    KeyFeatures: "Float flies, field events, club gatherings",
    Address: Address{
      Street: "26 Porter Rd (Eldon area events listed)",
      City: "Eldon",
      State: "MO",
      Zip: "",
    },
    Latitude: 0,
    Longitude: 0,
    AmaChartered: false,
    Driving: false,
    Flying: true,
    Boating: true,
  },
  {
    Id: "27",
    Name: "Sunchasers (North Kansas City area)",
    BriefDescription: "North Kansas City / Northland club with a long regional history and multiple event types.",
    WebsiteUrl: "https://www.rc-airplane-world.com/missouri-rc-airplane-clubs.html",
    Location: "North Kansas City / Kansas City, MO",
    KeyFeatures: "Grass field, club contests, public fly-ins",
    Address: Address{
      Street: "Woodland Rd (just north of Hwy 291)",
      City: "North Kansas City",
      State: "MO",
      Zip: "",
    },
    Latitude: 0,
    Longitude: 0,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "28",
    Name: "Radio Control Sport Flyers (Longview Lake / Grandview area)",
    BriefDescription: "Regional club operating at Longview Lake Park fields — community events & instruction.",
    WebsiteUrl: "http://www.rcsportflyers.com/",
    Location: "Grandview / Longview Lake area, MO",
    KeyFeatures: "Local events, instruction, family-friendly flying",
    Address: Address{
      Street: "Stamm Field, Longview Lake Park",
      City: "Grandview",
      State: "MO",
      Zip: "",
    },
    Latitude: 0,
    Longitude: 0,
    AmaChartered: false,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "29",
    Name: "Mount Vernon / Cedar County Modelers",
    BriefDescription: "Southwest MO local club for field flying, seasonal events and social meetups.",
    WebsiteUrl: "",
    Location: "Mount Vernon area, MO",
    KeyFeatures: "Local flying, community meetups",
    Address: Address{
      Street: "",
      City: "Mount Vernon",
      State: "MO",
      Zip: "",
    },
    Latitude: 0,
    Longitude: 0,
    AmaChartered: false,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "30",
    Name: "Signal Chasers RC Club",
    BriefDescription: "Pacific / Franklin County club with active membership and flying field.",
    WebsiteUrl: "",
    Location: "Pacific, MO",
    KeyFeatures: "Local flying site, instruction, member events",
    Address: Address{
      Street: "2499 Bend Rd",
      City: "Pacific",
      State: "MO",
      Zip: "63069",
    },
    Latitude: 0,
    Longitude: 0,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "31",
    Name: "Kansas City Northern Knights MAC",
    BriefDescription: "Kansas City northern-area club with a park/field site and member training programs.",
    WebsiteUrl: "https://northernknights.com/",
    Location: "Kansas City, MO",
    KeyFeatures: "Member training, community events, park flying",
    Address: Address{
      Street: "Hodge Park (7201 NE 96th St listed as club site)",
      City: "Kansas City",
      State: "MO",
      Zip: "64156",
    },
    Latitude: 39.263522,
    Longitude: -94.496031,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "32",
    Name: "KCHeli (Helicopter pilots group)",
    BriefDescription: "Helicopter-focused group in the KC metro providing a heli-specific flying area and pilot training.",
    WebsiteUrl: "",
    Location: "Lee's Summit / KC metro, MO",
    KeyFeatures: "Helicopter pilot community, 3D practice, instruction",
    Address: Address{
      Street: "2346 SW Sampson Rd (general region listed for club activities)",
      City: "Lee's Summit",
      State: "MO",
      Zip: "64082",
    },
    Latitude: 0,
    Longitude: 0,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "33",
    Name: "Cameron Dragonflies RC",
    BriefDescription: "Local club around Cameron, MO for RC pilots in the northwestern region of the state.",
    WebsiteUrl: "",
    Location: "Cameron, MO",
    KeyFeatures: "Local field flying & community activities",
    Address: Address{
      Street: "",
      City: "Cameron",
      State: "MO",
      Zip: "",
    },
    Latitude: 0,
    Longitude: 0,
    AmaChartered: false,
    Driving: false,
    Flying: true,
    Boating: false,
  },
  {
    Id: "34",
    Name: "Ozark Flyers (Hank Chenault Memorial Field and others)",
    BriefDescription: "Regional Ozarks club(s) with multiple fields and a history of community events.",
    WebsiteUrl: "https://www.modelaircraft.org/club/ozark-flyers",
    Location: "Various (Springfield / Ozarks region), MO",
    KeyFeatures: "Local contests, float & field flying, community events",
    Address: Address{
      Street: "",
      City: "Springfield / region",
      State: "MO",
      Zip: "",
    },
    Latitude: 0,
    Longitude: 0,
    AmaChartered: true,
    Driving: false,
    Flying: true,
    Boating: true,
  },
  {
    Id: "35",
    Name: "Western Missouri / Joplin area clubs (examples)",
    BriefDescription: "Multiple local clubs and tracks in the Joplin / southwest Missouri region supporting both aircraft and RC car activities.",
    WebsiteUrl: "https://rctracks.io/rc-tracks/united-states/missouri/",
    Location: "Joplin / Southwest MO",
    KeyFeatures: "RC car tracks, club flying, community meetups",
    Address: Address{
      Street: "",
      City: "Joplin",
      State: "MO",
      Zip: "",
    },
    Latitude: 0,
    Longitude: 0,
    AmaChartered: false,
    Driving: true,
    Flying: true,
    Boating: false,
  },
}

func (d *mockDB) GetClubs() []Club {
	clubs := make([]Club, len(mockClubs))
	copy(clubs, mockClubs[:]) // Prevent mutation of our mock data
	return clubs
}

func (d *mockDB) SetupDatabase() error {
	return nil
}
